#!/bin/sh
#
# gen_host_def_h.sh -- generate C++ include header based off of host.def
#
# Author: Nicholas Vining (mordred@lokigames.com)
#
# More strangeness from the build process.

# Run host.def; grab exports

. ../host.def

# Actually generate the .h file

echo "// this file was automatically generated by gen_host_def_h.sh" > host_def.h
echo "" >> host_def.h
echo "#ifndef __HOST_DEF_H" >> host_def.h
echo "#define __HOST_DEF_H" >> host_def.h
echo "" >> host_def.h

echo "#define _GEN_HOSTDEF_SUPPORT_EMAIL \"$support_email\"" >> host_def.h
echo "#define _GEN_HOSTDEF_KEY_FILE \"$publickeyfile\"" >> host_def.h

echo "#define _GEN_HOSTDEF_SUPPORT_DIRECTORY \"$support_directory\"" >> host_def.h
echo "#define _GEN_HOSTDEF_SIDEBAR_PIXMAP \"$sidebar_pixmap\"" >> host_def.h


echo "#define QAGENT_INTRO_PAGE ($intro_page)" >> host_def.h
echo "#define QAGENT_PATH_PAGE ($path_page)" >> host_def.h
echo "#define QAGENT_PRODUCT_PAGE ($product_page)" >> host_def.h
echo "#define QAGENT_SCAN_PAGE ($scan_page)" >> host_def.h
echo "#define QAGENT_FINDINGS_PAGE ($findings_page)" >> host_def.h
echo "#define QAGENT_COMMENT_PAGE ($comment_page)" >> host_def.h
echo "#define QAGENT_CONTACT_PAGE ($contact_page)" >> host_def.h
echo "#define QAGENT_DISPATCH_PAGE ($dispatch_page)" >> host_def.h
echo "#define QAGENT_FENRIS_PAGE ($fenris_page)" >> host_def.h
echo "#define QAGENT_NOGPG_PAGE ($nogpg_page)" >> host_def.h
echo "#define QAGENT_FILE_PAGE ($file_page)" >> host_def.h
echo "#define QAGENT_POLICY_PAGE ($policy_page)" >> host_def.h
echo "#define QAGENT_FINAL_CHECK_PAGE ($final_check_page)" >> host_def.h
echo "#define QAGENT_FINISHED_PAGE ($finished_page)" >> host_def.h

echo "" >> host_def.h
echo "#endif" >> host_def.h

